language: csharp
mono: latest
dotnet: 3.1.200
before_install:
- sudo apt-get install nunit-console
script:
- dotnet restore
- msbuild
- dotnet test ./Test/bin/Debug/netcoreapp3.1/Test.dll
 deploy:
  provider: heroku
  api_key:
    secure: abf38497-f5de-4826-a9ee-23ae4ae9d175
  app: api-deploy-test
  on:
    repo: purukumar16/TravisCI_Test
