language: csharp
mono: latest
dotnet: 3.1.200
before_install:
- sudo apt-get install nunit-console
script:
- dotnet restore
- msbuild
- dotnet test ./Test/bin/Debug/netcoreapp3.1/Test.dll
deploy:
  provider: heroku
  api_key:
    secure: km7oV5lISb0gHnnWAZFyBn/I8dXiLoPToKLAcQ3R63WDo8CrEKNSjxn2B2htM3L+abkGqyPwQISzOffvtb3Dj9pwVq5L7vUeoOl35+a050lY2XfqMQdlXDclpKHrR4Tt7m0pEXlFUPcrxY6YBYmqj2/e9V2wfuMNuDqpj2gV4yqVdA/etMykPePb9AI29O7OM6ARv8MM+h2/jzqlXmfUsDnwRIwuL18NYQps3bH+Jf45C9BGCQtlfArksfjhaD3IRk9cDR0qwwTT6g4C4pYWBfLTBi/V4qY9imk7iL34eARAjIq2XLsa37dfEcJEdGx39CntQYtndQmLnIXAe3bAJU9I87i+6ydbZNB0xsdVFfIrEMgJ+Fh/b+78FVGlRBm/i8bZ62Z6XQvfh+VgIj/trZy53R7aNUzNf5uQvSc6FUCzNYuiZssaPAJscAZ2ZhgEt9etiMMOG+0XZTwUmjVrfH9xYXar8nOVSNlzIRz1eQUW2avl5u4wQtxyYXUJlHv18k3ihMGNu/5Zwg/UAenMOUF8qTIAFIU0TmzHQupHPrh59GASx3/PBAWQJ0KI100gpAmUsN6OiCL74HEiZbGFXgkDgL+5qYt8u4H5iDWRt5gfF8+aSccOMs8+urGdn21Gh7drtBq09UnvxII6kQi4/z2YfeAf/0MOqd1Aw+ravEU=
  on:
    repo: purukumar16/TravisCI_Test
