language: csharp
mono: latest
dotnet: 3.1.200
before_install:
- sudo apt-get install nunit-console
script:
- dotnet restore
- msbuild
- dotnet test ./Test/bin/Debug/netcoreapp3.1/Test.dll
deploy:
  provider: heroku
api_key:
    secure: 4tuMeHRKD5Kg+ehz44QMlw8puxEBVYCZcI7QBW33kYi0i60c3+SLLyqnlCd6HWKiWfWxJdIZCiITWjPCTgVa4uS2SfQ8WklZU0kADyGAfl177I2Ga+nez5RRMbP1vdHQjW3igbklK0mNVCz0T0gHCv8In/AyJp2X8c/v+vNVfOU7rQkfnxM+WSOfT3UILDYzZ5cmAOc51G2jDeYE2Y4G5WrAPI0LXqnhHwSDJlehESgJiHcH6hz5qDW3P/raVPZQqFvg0HO+dlO9oQysMCZlFFoEnRzbo6WbCbsdZU9d+hXakOQ88ZVUYKW59n3G20/TT9+QeXwPUJeFBjdBtMmWD8O13dyHqJ62i9jb7DX6Ve7uEjnP+RwMQkHIN/sw2YUY/z6ta4PIwopBEMQC70AP1Ii64AMdt0uyIdm+mM35BD45e3NrHsot+3AoDEGD7gtBb6M0KNHj7SHtRJWkOAiwk6lfTJh465g1UFaCtJpHrrloOdDF6+EbUvNxpJCm8Kqv+rFS3AMZEO7pJdFM3NNeFhxIjOiI2w4zK8ox1LnH09Npg4IZSCisun+8zdFR3Vvv8kTe4SX0vWO9eu8a/cyjBdgs+BB/k5FqUPnqnyxL1OGgSG5v5+9V+IBEQg31NTego5cXaBQVMEyWuCTUBokcs6jOhzlM0dGrIwBQ6eqItgI=
  app:
  api-deploy-test
  on:
    repo: purukumar16/TravisCI_Test
