language: csharp
mono: latest
dotnet: 3.1.200
before_install:
- sudo apt-get install nunit-console
script:
- dotnet restore
- msbuild
- dotnet test ./Test/bin/Debug/netcoreapp3.1/Test.dll
deploy:
  provider: heroku
  api_key:
    secure: 10db00b9-74af-4fa0-a1ad-d47c36e6fdfd
  on:
    repo: purukumar16/TravisCI_Test
