language: csharp
mono: latest
dotnet: 3.1.200
before_install:
- sudo apt-get install nunit-console
script:
- dotnet restore
- msbuild
- dotnet test ./Test/bin/Debug/netcoreapp3.1/Test.dll
deploy:
  provider: heroku
  api_key:$HEROKU_API_KEY
  app:$HEROKU_APP_NAME
  true:
    repo: purukumar16/TravisCI_Test
